### PR TITLE
Add an assert to make sure this is only run on Dell servers

### PR DESCRIPTION
**Pull request by Klaas-**
Make sure this is not accidentally run on non-dell servers. In case you want to use it remotely from a non-dell server you can still overwrite it using a var

### CODE REVIEW

**Comment by martbhell** [comment]
Very handy thank you.

I pushed a change to master to fix the 'devel' testing. So if you want that to pass you may rebase this branch.
The test is however also failing because the assert runs also during test.
To make testing test more (and ideally pass) it looks like https://github.com/CSCfi/ansible-role-dell-firmware-upgrade/blob/master/tests/test.yml would the dell_dsu_assert: False under vars.
```

**Review by martbhell — CHANGES_REQUESTED** [review]
Very nice, only small thing is that I would like testing to test as much as possible - so would be nice to disable the assertion there.

**Comment by Klaas-** [comment]
@martbhell yeah I didn't check the CI results here cause they failed on the other PR aswell :) I'll fix them and rebase it

**Review by martbhell — APPROVED** [review]

**Comment by martbhell** [comment]
Now it passes, many thanks!

**Pull request merged**
