### PR TITLE
New exit code for "no new updates"

### PR DESCRIPTION
**Pull request by Klaas-**
dsu 1.6.0 introduced a new exit code for "no new updates"

### CODE REVIEW

**Review by martbhell — APPROVED** [review]
Seems so, thank you!
<pre>
# dsu --category=AS
DELL EMC System Update 1.6.0
Copyright (C) 2014 DELL EMC Proprietary.
Verifying catalog installation ...
Installing catalog from repository ...
Fetching dsucatalog ...
Reading the catalog ...
Verifying inventory collector installation ...
Getting System Inventory ...
warning: Inventory collector returned with partial failure.
Determining Applicable Updates ...
No Applicable Updates Available
Exiting DSU!
[root@myhost ~]# echo $?
34
</pre>

**Comment by Klaas-** [comment]
it's also in the official docs now: https://www.dell.com/support/manuals/us/en/04/system-update-v1.6.0/dsu_ug_1.6/dsu-return-codes?guid=guid-a413b447-0dd2-45fb-a60c-7a472e353e30&lang=en-us

**Comment by Klaas-** [comment]
I think I need to revisit this; I think this needs to be changed to something like this:
two vars
"valid exit codes" and "changed exit codes"; valid are the current ones for failed_when usage and 0,8 are for changed_when exit codes. Then I can see in my ansible output if firmware was actually changed or already in a good state

**Comment by martbhell** [comment]
Oh yeah, that sounds like a nice thing to have :)

**Pull request merged**
