### PR TITLE
testing: let's do some travis testing

### PR DESCRIPTION
**Pull request by martbhell**

### CODE REVIEW

**Review by khappone — APPROVED** [review]
Good idea. I.. think this works.

**Review by khappone — CHANGES_REQUESTED** [review]
I was wrong! tests fail. It seems it tries to run DSU, which fails since. well it's not Dell HW.

**Comment by martbhell** [comment]
Pushed a new commit, let's see if this works better.

**Comment by martbhell** [comment]
Okay this passes now :)

**Comment by khappone** [comment]
Great, merging.

**Pull request merged**
