### PR TITLE
Also rpm_key import GPG keys

### PR DESCRIPTION
**Pull request by martbhell**
Because I also need to get these GPG keys installed somehow.

If the keys are already installed then ansible is green. 
I guess this doesn't hurt to do as part of this role too?

 - #CCCP-2775

### CODE REVIEW

**Comment by Klaas-** [comment]
dsu does that upon launch when --import-public-key is supplied

plus rpm_key is not enough, you also need them in your gpg keyring

**Comment by Klaas-** [comment]
excerpt from the bootstrap script http://linux.dell.com/repo/hardware/dsu/bootstrap.cgi
```
install_gpg_key() {
    eval GPG_KEY_URL=${GPG_KEY_LOCATION}$1
    GPG_FN=$(mktemp /tmp/GPG-KEY-$$-XXXXXX)
    trap "rm -f $GPG_FN" EXIT HUP QUIT TERM
    curl -s -o ${GPG_FN} ${GPG_KEY_URL}
    email=$(gpg -v ${GPG_FN} 2>/dev/null  | grep -i @dell.com | sed 's/.*<\(.*\)>.*/\1/')
	
	set +e
	rpm -qa | grep gpg-pubkey | grep ${2,,} 2>/dev/null 1>/dev/null
	if [ $? -ne 0 ]; then
		if [ "${IMPORT_GPG_CONFIRMATION}" = "na" ]; then
			get_user_confirmation
		fi
		if [ "${IMPORT_GPG_CONFIRMATION}" = "yes" ]; then
			echo "    $1: Importing key into RPM."
			rpm --import ${GPG_FN} 2>/dev/null 1>/dev/null
			if [ $? -ne 0 ]; then
				echo "GPG-KEY import failed."
				echo "   Downloading the key failed or insufficient permissions to import the key."
				rm -f $GPG_FN
				exit 1
			fi
		else
			set -e
			rm -f $GPG_FN
			trap - EXIT HUP QUIT TERM
			return
		fi
	else
		echo "    $1: Key already exists in RPM, skipping"
	fi
	
	
	gpg --list-keys $2 2>/dev/null 1>/dev/null
	if [ $? -ne 0 ]; then
		if [ "${IMPORT_GPG_CONFIRMATION}" = "na" ]; then
			get_user_confirmation
		fi
		if [ "${IMPORT_GPG_CONFIRMATION}" = "yes" ]; then
			echo "                            Importing key into GPG."
			gpg --import ${GPG_FN} 2>/dev/null 1>/dev/null
			if [ $? -ne 0 ]; then
				echo "GPG-KEY import failed."
				echo "   Downloading the key failed or insufficient permissions to import the key."
				rm -f $GPG_FN
				exit 1
			fi
		fi
	else
		echo "                            Key already exists in GPG, skipping"
	fi
	
	
	set -e
    rm -f $GPG_FN
    trap - EXIT HUP QUIT TERM
}
```

**Comment by martbhell** [comment]
I need the GPG keys in rpm to be able to yum install DSU at all.

After that this role worked fine I think. I don't necessarily want to reinvent the GPG agent bit in this role, unless you see a benefit with that? 

We run this role without the bash pipe bit.

**Comment by Klaas-** [comment]
that should not be needed, you define the gpg keys in the yum.repos.d file and ansible auto-accepts them during install. But sure, you can explicitly put them into the ansible code - but then I'd say also define the gpg imports and then remove the import public key option

**Comment by martbhell** [comment]
> that should not be needed, you define the gpg keys in the yum.repos.d file and ansible auto-accepts them during install. But sure, you can explicitly put them into the ansible code - but then I'd say also define the gpg imports and then remove the import public key option

We use spacewalk and I'd like to avoid adding more stuff there and instead have more stuff in code.

While reading your comment I had a war flashback and remembered: https://github.com/CSCfi/ansible-role-dell
which I guess should be (like in this repo) updated to install the new GPG keys too. But I haven't used that repo in a long while so maybe it's not an issue there.

Added a task to this PR to also gpg --import the keys and remove the bit from dsu arguments. 
Couldn't quickly find an official GPG module in ansible so used command.

**Comment by Klaas-** [comment]
That looks good, I haven't tested it though, I'll give it a spin next time I need to upgrade a dell server.

But you should still consider adding the gpg keys to spacewalk, otherwise you can only use that repository after running ansible :)
I can't remember if spacewalk supports multiple gpg keys for a single repository though -- I know that's a limiting factor in satellite6/katello/pulp :)

**Pull request merged**
